#!/bin/bash

echo "Installing neo4j v4.4.20"
wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
echo 'deb https://debian.neo4j.com stable 4.4' | sudo tee /etc/apt/sources.list.d/neo4j.list
sudo apt-get update
sudo apt-get install -y neo4j=1:4.4.20
sudo systemctl enable neo4j
sudo neo4j-admin set-initial-password "neo4jubuntu@2023"
echo "Installation completed"

echo "Starting neo4j"
sudo neo4j start

sleep 5

echo "Launching Cypher shell"
cypher-shell -u neo4j -p neo4jubuntu@2023 -a neo4j://localhost:7687 --file Client/cypher-lexer-parser/queries/example/test.txt
